### ISSUE TITLE
6502 compatibility

### ISSUE THREAD

**Issue by f4goh** [nickgammon/G-Pascal#3]
Hello,
Is software compatible with classic MOS 6502 used in an Oric or i need absolutly WD65C02 ?

**Comment by nickgammon** [comment]
I saved a bit of effort by using the WD65C02 instruction set. That was what was on Ben Eater's board. You could modify it by replacing instructions that weren't on the WD65C02 set by their (lengthier) equivalents.

See <https://en.wikipedia.org/wiki/WDC_65C02>

For example, PHX,PLX,PHY,PLY.

You would have to replace those by transferring the register in question to A and then pushing it. And you would have to preserve A while you did that. So it is more tedious, but anything's possible!

**Comment by f4goh** [comment]
ok thanks.
